### ISSUE TITLE
in-game shop display error?

### ISSUE THREAD

**Issue by rsprbp** [AzuriomCommunity/Game-Flyff#11]
Resolved, writing webview :)

**Comment by rsprbp** [comment]
Resolved.

**Comment by Javdu10** [comment]
Hello, this error is because the website drop support with internet explorer.

To fix it you either need to make a custom theme that brings back support for internet explorer

OR

Modify your game source to change from internet explorer to WebView2

**Comment by rsprbp** [comment]
Ah so was indeed what I thought, thank you!
