### ISSUE TITLE
Can I separate the website from the game server or they need to be on the same machine?

### ISSUE THREAD

**Issue by Heriptik** [AzuriomCommunity/Game-Flyff#2]
Salut, simple question le cms doit être installé sur la machine qui execute le serveur flyff ou peut-on héberger le siteweb à distance ?

**Comment by Javdu10** [comment]
Salut @Heriptik !  les deux! La configuration est vraiment simple.
Certaines personnes l'utilisent sur la même machine avec une bdd mysql
D'autres ont un serveur de jeux et un petit serveur linux pour le site

> does the cms have to be installed on the machine running the flyff server or can the website be hosted remotely?

Hey! Both! The plugin configuration is really simple.
Some people use it on the same machine with a mysql database
Others have one game server (windows) and another little linux server for the website
